"""Initial migration

Revision ID: ee309898ab0f
Revises: 5f3ea3ef5ae7
Create Date: 2024-08-16 15:07:13.974613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee309898ab0f'
down_revision: Union[str, None] = '5f3ea3ef5ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapeddata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('headings', sa.JSON(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrapeddata')
    # ### end Alembic commands ###
